/**
 * [FINAL STABLE DATA] 지훈 대표님 프로젝트 - 150종 음료 데이터베이스
 * 중복 및 임의 생성 없이 실제 존재하는 메뉴로만 구성되었습니다.
 */

const drinkData = [
    // --- ☕ 커피 (COFFEE) - 30개 ---
    { name: "아메리카노", cat: "coffee", type: "hot", color: "#3d2b1f", desc: "깔끔하고 진한 풍미" },
    { name: "아이스 아메리카노", cat: "coffee", type: "ice", color: "#2b1b10", desc: "시원한 일상의 동반자" },
    { name: "카페라떼", cat: "coffee", type: "hot", color: "#d2b48c", desc: "부드러운 우유의 조화" },
    { name: "아이스 라떼", cat: "coffee", type: "ice", color: "#c19a6b", desc: "고소하고 시원한 맛" },
    { name: "바닐라 라떼", cat: "coffee", type: "ice", color: "#f3e5ab", desc: "달콤한 바닐라 향" },
    { name: "카라멜 마끼아또", cat: "coffee", type: "hot", color: "#c68e17", desc: "카라멜의 진한 달콤함" },
    { name: "카페모카", cat: "coffee", type: "hot", color: "#4b3621", desc: "초콜릿과 커피의 만남" },
    { name: "콜드브루", cat: "coffee", type: "ice", color: "#1a0f0a", desc: "깔끔한 뒷맛의 저온 추출" },
    { name: "아인슈페너", cat: "coffee", type: "ice", color: "#f5f5dc", desc: "달콤한 크림과 쌉쌀한 커피" },
    { name: "에스프레소", cat: "coffee", type: "hot", color: "#2b1b10", desc: "커피 본연의 강렬함" },
    { name: "플랫 화이트", cat: "coffee", type: "hot", color: "#decba4", desc: "진한 우유 거품의 매력" },
    { name: "돌체 라떼", cat: "coffee", type: "ice", color: "#fffdd0", desc: "연유의 부드러운 달콤함" },
    { name: "헤이즐넛 아메리카노", cat: "coffee", type: "ice", color: "#5d4037", desc: "고소한 견과류 향" },
    { name: "콘파냐", cat: "coffee", type: "hot", color: "#ffffff", desc: "생크림을 올린 에스프레소" },
    { name: "아포가토", cat: "coffee", type: "etc", color: "#fefefa", desc: "바닐라 아이스크림과 커피" },
    { name: "카푸치노", cat: "coffee", type: "hot", color: "#c3b091", desc: "풍성한 시나몬 가루" },
    { name: "더치 라떼", cat: "coffee", type: "ice", color: "#bda58d", desc: "부드러운 숙성 커피의 맛" },
    { name: "화이트 모카", cat: "coffee", type: "ice", color: "#f8f8ff", desc: "부드러운 화이트 초콜릿" },
    { name: "모카 프라페", cat: "coffee", type: "ice", color: "#6f4e37", desc: "얼음을 갈아 만든 커피" },
    { name: "오트 라떼", cat: "coffee", type: "hot", color: "#e3dac9", desc: "건강한 귀리 우유 사용" },
    { name: "코코넛 커피", cat: "coffee", type: "ice", color: "#fffafa", desc: "이국적인 코코넛의 향" },
    { name: "흑당 라떼", cat: "coffee", type: "ice", color: "#3e2723", desc: "진한 흑당 시럽의 풍미" },
    { name: "연유 커피", cat: "coffee", type: "hot", color: "#fff8e1", desc: "달콤하고 부드러운 목넘김" },
    { name: "에스프레소 마끼아또", cat: "coffee", type: "hot", color: "#4e342e", desc: "우유 거품을 살짝 올린 진한 맛" },
    { name: "디카페인 아메리카노", cat: "coffee", type: "ice", color: "#4e342e", desc: "카페인 부담 없는 깔끔함" },
    { name: "디카페인 라떼", cat: "coffee", type: "hot", color: "#d7ccc8", desc: "밤에도 즐기는 부드러움" },
    { name: "솔트 카라멜 라떼", cat: "coffee", type: "ice", color: "#dfbb9d", desc: "단짠단짠의 정석" },
    { name: "피스타치오 라떼", cat: "coffee", type: "ice", color: "#93c572", desc: "고소한 피스타치오 풍미" },
    { name: "민트 초코 라떼", cat: "coffee", type: "ice", color: "#00ffc5", desc: "상쾌한 민트와 달콤함" },
    { name: "토피넛 라떼", cat: "coffee", type: "hot", color: "#af8a54", desc: "견과류의 고소한 맛" },

    // --- 🍹 에이드 & 주스 (ADE/JUICE) - 40개 ---
    { name: "토마토주스", cat: "juice", type: "ice", color: "#e74c3c", desc: "신선한 완숙 토마토" },
    { name: "자몽에이드", cat: "ade", type: "ice", color: "#ff7f50", desc: "톡 쏘는 자몽의 상큼함" },
    { name: "레몬에이드", cat: "ade", type: "ice", color: "#fff44f", desc: "비타민 가득 레몬 즙" },
    { name: "청포도에이드", cat: "ade", type: "ice", color: "#a8e4a0", desc: "싱그러운 청포도 향" },
    { name: "오렌지주스", cat: "juice", type: "ice", color: "#ffa500", desc: "착즙 오렌지의 신선함" },
    { name: "수박주스", cat: "juice", type: "ice", color: "#ff3b3f", desc: "여름 무더위 해결사" },
    { name: "키위주스", cat: "juice", type: "ice", color: "#8eb915", desc: "상큼한 키위 알갱이" },
    { name: "딸기바나나주스", cat: "juice", type: "ice", color: "#fc8eac", desc: "딸바의 황금 비율" },
    { name: "블루베리에이드", cat: "ade", type: "ice", color: "#6a5acd", desc: "진한 블루베리 과육" },
    { name: "라임모히또(무알콜)", cat: "ade", type: "ice", color: "#00ff00", desc: "민트와 라임의 청량감" },
    { name: "깔라만시에이드", cat: "ade", type: "ice", color: "#ccff00", desc: "초강력 상큼 비타민" },
    { name: "한라봉에이드", cat: "ade", type: "ice", color: "#ff8c00", desc: "제주의 달콤한 향기" },
    { name: "유자에이드", cat: "ade", type: "ice", color: "#fff000", desc: "달콤 쌉싸름한 유자 청" },
    { name: "매실에이드", cat: "ade", type: "ice", color: "#4f7942", desc: "소화를 돕는 상큼함" },
    { name: "체리콕", cat: "ade", type: "ice", color: "#800000", desc: "체리와 콜라의 조화" },
    { name: "패션후르츠에이드", cat: "ade", type: "ice", color: "#ffd700", desc: "오독오독 씹히는 식감" },
    { name: "사과주스", cat: "juice", type: "ice", color: "#ff0800", desc: "아침을 여는 사과 한 알" },
    { name: "포도주스", cat: "juice", type: "ice", color: "#6f2da8", desc: "달콤하고 진한 포도 향" },
    { name: "당근주스", cat: "juice", type: "ice", color: "#ff8c00", desc: "건강을 담은 베타카로틴" },
    { name: "망고주스", cat: "juice", type: "ice", color: "#ffcc00", desc: "열대의 달콤한 맛" },
    { name: "파인애플주스", cat: "juice", type: "ice", color: "#ffff00", desc: "새콤달콤 파인애플" },
    { name: "배주스", cat: "juice", type: "ice", color: "#f5f5dc", desc: "갈증 해소에 탁월" },
    { name: "복숭아에이드", cat: "ade", type: "ice", color: "#ffcba4", desc: "달콤한 복숭아 향" },
    { name: "애플망고주스", cat: "juice", type: "ice", color: "#ff8a65", desc: "프리미엄 망고의 풍미" },
    { name: "깔라만시주스", cat: "juice", type: "ice", color: "#d4ff00", desc: "다이어트의 친구" },
    { name: "석류에이드", cat: "ade", type: "ice", color: "#c0392b", desc: "여성에게 좋은 석류" },
    { name: "홍자몽에이드", cat: "ade", type: "ice", color: "#ff4d4d", desc: "더 진한 루비자몽" },
    { name: "청귤에이드", cat: "ade", type: "ice", color: "#2e8b57", desc: "풋풋한 청귤의 향기" },
    { name: "오미자에이드", cat: "ade", type: "ice", color: "#dc143c", desc: "다섯 가지 맛의 조화" },
    { name: "블러드오렌지에이드", cat: "ade", type: "ice", color: "#8b0000", desc: "진하고 붉은 오렌지" },
    { name: "알로에주스", cat: "juice", type: "ice", color: "#98fb98", desc: "부드러운 알로에 겔" },
    { name: "코코넛워터", cat: "juice", type: "ice", color: "#ffffff", desc: "천연 이온 음료" },
    { name: "체리에이드", cat: "ade", type: "ice", color: "#de3163", desc: "달콤한 체리 시럽" },
    { name: "진저에일", cat: "ade", type: "ice", color: "#b8860b", desc: "알싸한 생강의 청량함" },
    { name: "박사(박카스+사이다)", cat: "ade", type: "ice", color: "#ffff33", desc: "피로 회복 에너지" },
    { name: "레몬밤에이드", cat: "ade", type: "ice", color: "#adff2f", desc: "허브 향 가득한 에이드" },
    { name: "머스캣주스", cat: "juice", type: "ice", color: "#90ee90", desc: "샤인머스캣의 달콤함" },
    { name: "비트당근주스", cat: "juice", type: "ice", color: "#8b008b", desc: "강력한 항산화 에너지" },
    { name: "깔라만시라임에이드", cat: "ade", type: "ice", color: "#7fff00", desc: "극강의 상큼 조합" },
    { name: "허니자몽블랙티(ICE)", cat: "ade", type: "ice", color: "#cd5c5c", desc: "홍차와 자몽의 만남" },

    // --- 🍵 티/차 (TEA) - 30개 ---
    { name: "얼그레이", cat: "tea", type: "hot", color: "#8e44ad", desc: "베르가못 향의 홍차" },
    { name: "캐모마일", cat: "tea", type: "hot", color: "#f1c40f", desc: "심신 안정 허브티" },
    { name: "페퍼민트", cat: "tea", type: "hot", color: "#1abc9c", desc: "입안 가득 상쾌함" },
    { name: "녹차", cat: "tea", type: "hot", color: "#2ecc71", desc: "차분한 녹차 잎의 맛" },
    { name: "루이보스", cat: "tea", type: "hot", color: "#e67e22", desc: "카페인 없는 붉은 차" },
    { name: "히비스커스", cat: "tea", type: "ice", color: "#e74c3c", desc: "새빨간 색의 상큼한 티" },
    { name: "자스민", cat: "tea", type: "hot", color: "#ffffff", desc: "우아한 꽃 향기" },
    { name: "잉글리쉬 블랙퍼스트", cat: "tea", type: "hot", color: "#3e2723", desc: "진하고 묵직한 홍차" },
    { name: "유자차", cat: "tea", type: "hot", color: "#f9d71c", desc: "겨울철 비타민 보충" },
    { name: "생강차", cat: "tea", type: "hot", color: "#bda58d", desc: "몸을 따뜻하게 보호" },
    { name: "대추차", cat: "tea", type: "hot", color: "#5d4037", desc: "진하고 달콤한 전통 차" },
    { name: "쌍화차", cat: "tea", type: "hot", color: "#2b1b10", desc: "견과류 가득 보양 차" },
    { name: "우롱차", cat: "tea", type: "hot", color: "#cd853f", desc: "깊고 그윽한 풍미" },
    { name: "보이차", cat: "tea", type: "hot", color: "#4e342e", desc: "세월을 머금은 깊은 맛" },
    { name: "마테차", cat: "tea", type: "ice", color: "#9acd32", desc: "남미의 건강 활력 차" },
    { name: "애플시나몬티", cat: "tea", type: "hot", color: "#a52a2a", desc: "사과와 계피의 향긋함" },
    { name: "라벤더티", cat: "tea", type: "hot", color: "#e6e6fa", desc: "편안한 잠을 위한 선택" },
    { name: "레몬글라스", cat: "tea", type: "hot", color: "#ccff00", desc: "싱그러운 레몬 향 허브" },
    { name: "로즈마리티", cat: "tea", type: "hot", color: "#006400", desc: "집중력을 높이는 향기" },
    { name: "말차라떼", cat: "tea", type: "ice", color: "#008000", desc: "진한 말차 가루와 우유" },
    { name: "밀크티", cat: "tea", type: "ice", color: "#c5a383", desc: "홍차 우린 우유의 정석" },
    { name: "타로밀크티", cat: "tea", type: "ice", color: "#dda0dd", desc: "고소한 보라색 타로" },
    { name: "말차슈페너", cat: "tea", type: "ice", color: "#556b2f", desc: "말차 위에 달콤한 크림" },
    { name: "대추생강차", cat: "tea", type: "hot", color: "#8b4513", desc: "환절기 필수 건강 차" },
    { name: "모과차", cat: "tea", type: "hot", color: "#fada5e", desc: "목에 좋은 달콤한 모과" },
    { name: "둥굴레차", cat: "tea", type: "hot", color: "#deb887", desc: "구수한 매력의 전통 차" },
    { name: "메밀차", cat: "tea", type: "hot", color: "#f5deb3", desc: "가볍고 구수한 맛" },
    { name: "로즈힙티", cat: "tea", type: "ice", color: "#ff69b4", desc: "붉은 장미 열매의 상큼함" },
    { name: "콤부차(레몬)", cat: "tea", type: "ice", color: "#fcfc5d", desc: "발효차의 청량한 탄산" },
    { name: "콤부차(베리)", cat: "tea", type: "ice", color: "#ff007f", desc: "베리류의 달콤 발효" },

    // --- 🍦 스무디 & 기타 (SMOOTHIE/ETC) - 30개 ---
    { name: "딸기스무디", cat: "smoothie", type: "ice", color: "#ff4d6d", desc: "상큼한 딸기 얼음" },
    { name: "망고스무디", cat: "smoothie", type: "ice", color: "#ffcc33", desc: "부드러운 열대 망고" },
    { name: "블루베리스무디", cat: "smoothie", type: "ice", color: "#483d8b", desc: "눈이 맑아지는 블루베리" },
    { name: "요거트스무디", cat: "smoothie", type: "ice", color: "#ffffff", desc: "플레인 요거트의 상큼함" },
    { name: "딸기요거트스무디", cat: "smoothie", type: "ice", color: "#ffb6c1", desc: "요거트와 딸기의 환상 궁합" },
    { name: "망고요거트스무디", cat: "smoothie", type: "ice", color: "#ffe135", desc: "부드럽고 달콤한 조합" },
    { name: "초코스무디", cat: "smoothie", type: "ice", color: "#3e2723", desc: "극강의 초코 달콤함" },
    { name: "민트초코프라페", cat: "smoothie", type: "ice", color: "#afeeee", desc: "민초파 모여라" },
    { name: "그린티프라페", cat: "smoothie", type: "ice", color: "#228b22", desc: "쌉싸름한 녹차 얼음" },
    { name: "쿠키앤크림프라페", cat: "smoothie", type: "ice", color: "#f5f5f5", desc: "쿠키가 씹히는 달콤함" },
    { name: "자바칩프라페", cat: "smoothie", type: "ice", color: "#4b3621", desc: "초콜릿 칩의 오독오독함" },
    { name: "미숫가루스무디", cat: "smoothie", type: "ice", color: "#cdaa7d", desc: "식사 대용 고소한 음료" },
    { name: "팥스무디", cat: "smoothie", type: "ice", color: "#673147", desc: "빙수 대신 마시는 팥" },
    { name: "수박스무디", cat: "smoothie", type: "ice", color: "#ff5a5f", desc: "시원한 수박의 결정체" },
    { name: "멜론스무디", cat: "smoothie", type: "ice", color: "#9af310", desc: "달콤한 메론 향 가득" },
    { name: "피치스무디", cat: "smoothie", type: "ice", color: "#ff9999", desc: "복숭아 과육의 부드러움" },
    { name: "밀크쉐이크", cat: "etc", type: "ice", color: "#fffafa", desc: "우유 본연의 고소한 맛" },
    { name: "바닐라쉐이크", cat: "etc", type: "ice", color: "#f3e5ab", desc: "부드러운 바닐라 향기" },
    { name: "딸기쉐이크", cat: "etc", type: "ice", color: "#ffc0cb", desc: "분홍빛 달콤한 쉐이크" },
    { name: "초코쉐이크", cat: "etc", type: "ice", color: "#7b3f00", desc: "진하고 걸쭉한 초코" },
    { name: "커피쉐이크", cat: "etc", type: "ice", color: "#a52a2a", desc: "더위사냥 같은 맛" },
    { name: "고구마라떼", cat: "etc", type: "hot", color: "#6a0dad", desc: "든든하고 달콤한 자색고구마" },
    { name: "단호박라떼", cat: "etc", type: "hot", color: "#ff8c00", desc: "달콤하고 부드러운 호박" },
    { name: "핫초코", cat: "etc", type: "hot", color: "#3e2723", desc: "겨울철 필수 당 충전" },
    { name: "아이스초코", cat: "etc", type: "ice", color: "#4b3621", desc: "당 충전용 아이스 음료" },
    { name: "밤라떼", cat: "etc", type: "hot", color: "#8b4513", desc: "가을의 고소함을 담은 맛" },
    { name: "곡물라떼", cat: "etc", type: "hot", color: "#d2b48c", desc: "12가지 곡물의 영양" },
    { name: "쑥라떼", cat: "etc", type: "hot", color: "#2f4f4f", desc: "할매니얼 취향 저격" },
    { name: "초코민트스무디", cat: "smoothie", type: "ice", color: "#00ced1", desc: "상쾌함의 끝판왕" },
    { name: "코코넛스무디커피", cat: "smoothie", type: "ice", color: "#fffaf0", desc: "베트남식 코코넛 커피" },

    // --- 🍺 주류 (ALCOHOL) - 20개 ---
    { name: "생맥주", cat: "alcohol", type: "ice", color: "#ffbf00", desc: "시원한 목넘김의 정석" },
    { name: "하이볼(산토리)", cat: "alcohol", type: "ice", color: "#f4c430", desc: "위스키와 탄산수의 조화" },
    { name: "레몬하이볼", cat: "alcohol", type: "ice", color: "#fff44f", desc: "상큼함이 배가된 하이볼" },
    { name: "진토닉", cat: "alcohol", type: "ice", color: "#f0f8ff", desc: "깔끔하고 세련된 칵테일" },
    { name: "모히또(알콜)", cat: "alcohol", type: "ice", color: "#32cd32", desc: "라임과 럼의 환상 조화" },
    { name: "잭콕", cat: "alcohol", type: "ice", color: "#000000", desc: "잭다니엘과 콜라의 만남" },
    { name: "피치크러쉬", cat: "alcohol", type: "ice", color: "#ff1493", desc: "복숭아 향의 달콤함" },
    { name: "깔루아밀크", cat: "alcohol", type: "ice", color: "#5d4037", desc: "커피우유 같은 칵테일" },
    { name: "말리부오렌지", cat: "alcohol", type: "ice", color: "#ffa500", desc: "코코넛과 오렌지의 이국적 맛" },
    { name: "샹그리아", cat: "alcohol", type: "ice", color: "#800020", desc: "와인에 담긴 과일 풍미" },
    { name: "레드와인", cat: "alcohol", type: "etc", color: "#722f37", desc: "분위기 있는 저녁 한 잔" },
    { name: "화이트와인", cat: "alcohol", type: "etc", color: "#f5deb3", desc: "해산물과 잘 어울리는 맛" },
    { name: "스파클링와인", cat: "alcohol", type: "ice", color: "#ffffcc", desc: "특별한 날을 위한 기포" },
    { name: "소맥", cat: "alcohol", type: "ice", color: "#fada5e", desc: "한국인의 소울 드링크" },
    { name: "얼그레이하이볼", cat: "alcohol", type: "ice", color: "#8b4513", desc: "트렌디한 홍차 하이볼" },
    { name: "코스모폴리탄", cat: "alcohol", type: "ice", color: "#e30b5d", desc: "세련된 핑크빛 칵테일" },
    { name: "블루하와이", cat: "alcohol", type: "ice", color: "#0000ff", desc: "푸른 바다의 청량함" },
    { name: "자몽생맥주", cat: "alcohol", type: "ice", color: "#ff6347", desc: "과일 향 가득한 맥주" },
    { name: "막걸리", cat: "alcohol", type: "ice", color: "#f5f5dc", desc: "한국 전통 발효주의 고소함" },
    { name: "청하", cat: "alcohol", type: "ice", color: "#ffffff", desc: "부드럽고 깔끔한 정종" }
];